name: ioc_flow
description: A package that offers a declarative way for inversion of control and allows refreshing dependencies in the ioc container automatically.
version: 0.0.1+1-alpha
homepage: https://github.com/folaoluwafemi/ioc_flow
repository: https://github.com/folaoluwafemi/ioc_flow

environment:
  sdk: '>=3.0.2 <4.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0